services:
  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/informatica-na-presales-ops/zendesk-api
    init: true
    volumes:
      - ./:/app

  zendesk-api:
    image: ghcr.io/informatica-na-presales-ops/zendesk-api
    init: true
