services:
  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile
    image: ghcr.io/williamjacksn/pip-tools:py3.12
    init: true
    volumes:
      - ./:/home/python/zendesk-api
    working_dir: /home/python/zendesk-api

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/informatica-na-presales-ops/zendesk-api
    init: true
    volumes:
      - ./:/home/python/zendesk-api
    working_dir: /home/python/zendesk-api

  zendesk-api:
    image: ghcr.io/informatica-na-presales-ops/zendesk-api
    init: true
