PUT https://{{company}}.zendesk.com/api/v2/deleted_tickets/{{ticket_id}}/restore.json
Authorization: Basic {{email}} {{token}}

###

GET https://{{company}}.zendesk.com/api/v2/group_memberships.json?page[size]=100
Authorization: Basic {{email}} {{token}}

###

GET https://{{company}}.zendesk.com/api/v2/groups.json?page[size]=100
Authorization: Basic {{email}} {{token}}

###

GET https://{{company}}.zendesk.com/api/v2/incremental/tickets/cursor.json?start_time=946684800&per_page=1
Authorization: Basic {{email}} {{token}}

###

GET https://{{company}}.zendesk.com/api/v2/organization_memberships.json
Authorization: Basic {{email}} {{token}}

###

GET https://{{company}}.zendesk.com/api/v2/organizations.json?page[size]=100
Authorization: Basic {{email}} {{token}}

###

GET https://{{company}}.zendesk.com/api/v2/search.json?sort_by=updated_at&sort_order=asc&query=type:ticket+status<solved+updated<2020-04-28
Authorization: Basic {{email}} {{token}}

###

GET https://{{company}}.zendesk.com/api/v2/search.json?query=type:ticket+tags:tag-to-search-for
Authorization: Basic {{email}} {{token}}

###

GET https://{{company}}.zendesk.com/api/v2/ticket_fields.json
Authorization: Basic {{email}} {{token}}

###

GET https://{{company}}.zendesk.com/api/v2/ticket_fields/{{ticket_field_id}}/options.json
Authorization: Basic {{email}} {{token}}

###

POST https://{{company}}.zendesk.com/api/v2/ticket_fields/{{ticket_field_id}}/options.json
Authorization: Basic {{email}} {{token}}
Content-Type: application/json

{
  "custom_field_option": {
    "id": {{ticket_field_option_id}},
    "name": "New Product Name Renamed"
  }
}

###

DELETE https://{{company}}.zendesk.com/api/v2/ticket_fields/{{ticket_field_id}}/options/{{ticket_field_option_id}}.json
Authorization: Basic {{email}} {{token}}


###

POST https://{{company}}.zendesk.com/api/v2/tickets
Authorization: Basic {{email}} {{token}}
Content-Type: application/json

{
  "ticket": {
    "comment": {
      "body": "Test ticket"
    }
  }
}

###

GET https://{{company}}.zendesk.com/api/v2/tickets/{{ticket_id}}.json
Authorization: Basic {{email}} {{token}}

###

PUT https://{{company}}.zendesk.com/api/v2/tickets/update_many.json?ids={{ticket_id}}
Authorization: Basic {{email}} {{token}}

{
  "ticket": {
    "remove_tags": ["tag-to-remove"],
    "additional_tags": ["tag-to-add"]
  }
}

###

GET https://{{company}}.zendesk.com/api/v2/users.json?page[size]=100
Authorization: Basic {{email}} {{token}}

###

GET https://{{company}}.zendesk.com/api/v2/users/{{user_id}}.json
Authorization: Basic {{email}} {{token}}

###

GET https://{{company}}.zendesk.com/api/v2/users/{{user_id}}/group_memberships.json
Authorization: Basic {{email}} {{token}}

###

PUT https://{{company}}.zendesk.com/api/v2/users/{{user_id}}.json
Authorization: Basic {{email}} {{token}}
Content-Type: application/json

{
  "user": {
    "external_id": null
  }
}

###
