name: Build the container image

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      push_image:
        description: Push latest image
        required: true
        type: boolean

env:
  image_name: ghcr.io/informatica-na-presales-ops/zendesk-api

jobs:

  build:
    name: Build the container image
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.3.0

      - name: Build the container image
        uses: docker/build-push-action@v3.3.0
        with:
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          cache-from: |
            ${{ env.image_name }}
          load: true
          tags: ${{ env.image_name }}

      - name: Log in to GitHub container registry
        if: github.event_name == 'push' || github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.push_image)
        uses: docker/login-action@v2.1.0
        with:
          password: ${{ github.token }}
          registry: ghcr.io
          username: ${{ github.actor }}

      - name: Push latest image to registry
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.push_image)
        run: docker image push ${{ env.image_name }}

      - name: Tag and push release image to registry
        if: github.event_name == 'release'
        run: |
          docker image tag ${{ env.image_name }}:latest ${{ env.image_name }}:${{ github.event.release.tag_name }}
          docker image push ${{ env.image_name }}:${{ github.event.release.tag_name }}
